### PR TITLE
Styling for handover opt-out page

### PR DESCRIPTION
**Pull request by zarino**
**This is not ready to deploy** – it needs someone (@osfameron?) to take my styles and markup changes, and merge them into the existing templates.

 hassleme

### CODE REVIEW

**Comment by osfameron** [comment]
Woo, that looks awesome.  I'll see if I can get that integrated before the
call tomorrow, thanks!

Hakim
-- 
*Developer*, mySociety Services
http://www.mysociety.co.uk

**Comment by osfameron** [comment]
Tweaked in the breakaway branch, and deployed to new.hassleme.

But I've not deleted the `T/` temporary directory (in case @zarino needs to do any revisions)
nor merged into master (as I need to rebase against part of @dracos's recent changes first).

By the way, "Gill Sans" looks remarkably silly in Windows/Chrome due to https://code.google.com/p/chromium/issues/detail?id=408093 :-(

**Comment by zarino** [comment]
Good spot @osfameron. Looks like the solution is to define "Gill Sans MT" before "Gill Sans" in the font-family declaration. I'll do that when I'm back at my computer.

**Comment by osfameron** [comment]
Zarino's original pull was integrated into HasslMe:breakaway with tweaks.  Will issue separate pull request for all work.

**Pull request closed without merging**
